# Generated by Django 5.2.6 on 2025-09-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="personfilmwork",
            name="film_work_person_role_idx",
        ),
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work_id", "person_id", "role"),
                name="film_work_person_role_idx",
            ),
        ),
    ]
